### ISSUE TITLE
Anonymous communication over XMPP

### ISSUE THREAD

**Issue by PeterWaher** [Trust-Anchor-Group/NeuroAccessMaui#45]
The app can now create accounts of the form GUID@domain for users who wish that basic addressing over XMPP is done anonymously. When logging in using QuickLogin on Neurons, instead of the account name, the e-mail address is shown as user name, if an ID with a proper name is not available. If no e-mail address is available, the phone number is presented. The GUID will only be presented if the account lacks an ID with proper name, email or phone number.

So, the user should have the option of choosing these three basic levels of identification on XMPP:

1. Real name (account name based on person's name). If providing a name in the ID, these should be set as the **default** values when later applying for a new ID

2. Pseudonymously, using a nickname (account name based on nickname). If providing a nickname, it should be embedded into presence subscriptions, after any legal ID available. It should also be possible to edit and change the nickname from the settings menu. This will not affect the account name however.

3. Anonymously, using a GUID as the local part of the account. When performing a quick-login, the real name from the ID will be presented (if available), if not, the e-mail, and if no e-mail available, the phone number, and as a last resort, the GUID.

**Comment by berggrenmille** [comment]
In the case for pseudonyms "it should be embedded into presence subscriptions" I agree, but should not the real name do so aswell. In case of providing real name you have already accepted that this might be exposed in communication, so should this not then per default become the "nickname", so it can be viewed in a more friendly way

**Comment by PeterWaher** [comment]
> @PeterWaher In the case for pseudonyms "it should be embedded into presence subscriptions" I agree, but should not the real name do so aswell. In case of providing real name you have already accepted that this might be exposed in communication, so should this not then per default become the "nickname", so it can be viewed in a more friendly way

The public legal ID is included in the presence subscription request as it is. The real name will be available there. The ID XML just needs to be appended with the nick-name-XML, which the XmppClient can generate for you.

**Comment by berggrenmille** [comment]
Closing this issue as we have for the time settled for accepting only username in the onboarding
